name: wave_mobile
description: Application mobile Wave
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  intl: ^0.18.0
  smooth_page_indicator: ^1.2.0+3
  permission_handler: ^11.3.1
  fl_chart: ^0.65.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  go_router: ^6.0.1
  dio: ^5.7.0
  carousel_slider: ^4.2.1
  flutter_contacts: ^1.1.7
  

flutter_icons:
  android: "launcher_icon.png"
  ios: "launcher_icon.png"
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700